### ISSUE TITLE
Cannot register plugin

### ISSUE THREAD

**Issue by shermelin** [CEMES-CNRS/pymodaq_plugins_template#2]
Hi Sébastien,

I'm trying to implement a plugin for attocube hardware but run fairly early into troubles trying to install a plugin.

The plugin_manager chokes on a NoneType when trying to load the freshly installed plugin (from your template).
Printing "d" from pymodaq_plugin_manager/validate.py, line 120, I get :

```
{'plugin-name': 'pymodaq_plugins', 'display-name': 'Default', 'version': '3.0.2', 'id': '52000a1191dbf8e9903708b77ac3fa82a3c41d91af328ad5d0362c4d449cdebe', 'repository': 'https://github.com/CEMES-CNRS/pymodaq_plugins/archive/3.0.1.tar.gz', 'description': 'Plugins initially developed with PyMoDAQ\r\nIncludes Mock plugins that are plugins of virtual instruments dedicated to code testing a new functionalities development. The list of included plugins can be found on https://docs.google.com/spreadsheets/d/1wfMfvLwTitZd2R2m1O5i6wVEaX1lJBahP2HUbxVdidg', 'instruments': {'Actuator': ['Mock actuator to test PyMoDAQ functionnalities', 'TCP server to communicate with other DAQ_Move or third party applications'], 'Viewer0D': ['Mock detector to test PyMoDAQ functionnalities', 'Mock detector to test PyMoDAQ adaptive scan mode', 'TCP server to communicate with other DAQ_Viewer or third party applications'], 'Viewer1D': ['Mock detector to test PyMoDAQ functionnalities', 'Mock detector to test pymodaq_spectro functionalities', 'TCP server to communicate with other DAQ_Viewer or third party applications'], 'Viewer2D': ['Mock detector to test PyMoDAQ functionnalities', 'TCP server to communicate with other DAQ_Viewer or third party applications'], 'ViewerND': ['Mock actuator to test PyMoDAQ functionnalities']}, 'authors': ['Sebastien Weber'], 'contributors': [], 'homepage': 'https://github.com/CEMES-CNRS/pymodaq_plugins'}
{'plugin-name': 'pymodaq_plugins_thorlabs', 'display-name': 'Thorlabs Instruments', 'version': '0.0.1', 'id': '562ef6ea46d9dc326db4448a8e314b815d363f1edcca4eeb6434d36ba8654d76', 'repository': 'https://github.com/CEMES-CNRS/pymodaq_plugins_thorlabs/archive/0.0.1.tar.gz', 'description': 'Set of PyMoDAQ plugins for instruments from Thorlabs (Kinesis K10CR1 (stepper rotation actuator), Kinesis Flipper, Kinesis KSP100...)', 'instruments': {'Actuator': ['Kinesis serie (tested on K10CR1 and Flipper)'], 'Viewer0D': ['Kinesis KPA101 Position Sensing Detector']}, 'authors': ['Sebastien Weber'], 'contributors': [], 'homepage': 'https://github.com/CEMES-CNRS/pymodaq_plugins_thorlabs'}
{'plugin-name': 'pymodaq_plugins_smaract', 'display-name': 'Smaract', 'version': '0.0.1', 'id': 'eb8c349bb16aa8c538b10617fb0af5bd8562c3f24e28a5c2a0f92e12fcdec18c', 'repository': 'https://github.com/CEMES-CNRS/pymodaq_plugins_smaract/archive/0.0.1.tar.gz', 'description': 'Set of PyMoDAQ plugins for Actuators from Smaract (MCS_controller, ...)', 'instruments': {'Actuator': ['Actuators driven using the MCS controller and its library']}, 'authors': ['David Bresteau'], 'contributors': [], 'homepage': 'https://github.com/CEMES-CNRS/pymodaq_plugins_smaract'}
{'plugin-name': 'pymodaq_plugins_andor', 'display-name': 'Andor', 'version': '0.0.1', 'id': '9f2ce447a5a400e3c9457877d1cc9e138906e053344d2b4c3bb3aa20e7de033a', 'repository': 'https://github.com/CEMES-CNRS/pymodaq_plugins_andor/archive/0.0.1.tar.gz', 'description': 'Set of PyMoDAQ plugins for Andor Camera (CCD camera using SDK2, SCMOS cameras using SDK3...)', 'instruments': {'Viewer1D': ['Shamrock series of spectrometer using the Andor CCD cameras'], 'Viewer2D': ['Andor CCD camera using the SDK2']}, 'authors': ['Sebastien Weber'], 'contributors': [], 'homepage': 'https://github.com/CEMES-CNRS/pymodaq_plugins_andor'}
None
Traceback (most recent call last):
  File "/home/shermelin/Documents/projets/035_pymodaq/venv/lib/python3.8/site-packages/pymodaq/dashboard.py", line 288, in start_plugin_manager
    self.plugin_manager = PluginManager(widget)
  File "/home/shermelin/Documents/projets/035_pymodaq/venv/lib/python3.8/site-packages/pymodaq_plugin_manager/manager.py", line 114, in __init__
    self.plugins_available, self.plugins_installed, self.plugins_update = get_plugins()
  File "/home/shermelin/Documents/projets/035_pymodaq/venv/lib/python3.8/site-packages/pymodaq_plugin_manager/validate.py", line 122, in get_plugins
    d.update(plug)
AttributeError: 'NoneType' object has no attribute 'update'
```

There is obviously something missing from the template plugin I just installed, but cannot find what... any help?

Thanks

**Comment by seb5g** [comment]
Hello,
the new plugins have to be added in the plugin_manager internal data list for the install using this method to work. The easiest if you're already developer is to install it manually and in editable mode. In an activated environment, ``cd`` to the location of the setup.py of you plugin and type in the console:  ``pip install -e .`` This will install it. If no error during loading it should then appear in the list in the DAQ_Move GUI. 
Once you're happy with your plugin, please let me know and we will add it to the plugin_manager list !
Regards

**Comment by shermelin** [comment]
THANKS! I was installing with `python setup.py install` which obviously does not do the exact same job....

I did not know editable mode. You just made my life much easier! thanks!
